name: Bug Report
description: Unexpected extraction output, crash, or invariant violation
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please fill out as much as possible — the more context you provide, the faster we can diagnose it.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the unexpected behavior.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What output or behavior did you expect instead?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Minimal reproduction
      description: |
        Paste the minimal Angular route/component/template that triggers the issue,
        OR a link to a reproduction repo.
      render: typescript
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Package version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: "20.x"
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Frontend framework
      options:
        - Angular
        - React
        - Vue
        - Other / Unknown
    validations:
      required: true

  - type: textarea
    id: bundle_excerpt
    attributes:
      label: Relevant Phase1AnalysisBundle excerpt (if available)
      description: Paste the affected node/edge/widget/route from the output JSON.
      render: json
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
    validations:
      required: false
